spring:
  profiles:
    include:
    - common-dev

mybatis:
  type-aliases-package: com.scnu.zwebapp.zwebapp.bean
  mapper-locations: classpath:mapper/**.xml,classpath:mapper/ext/**.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    
dubbo:
  application:
    name: zwebapp-flow   # dubbo应用名称
  registry:
    protocol: zookeeper      # 注册中心协议
    address: 127.0.0.1:2181  # 注册中心地址
  protocol:
    name: dubbo
    port: 20081
  monitor:
    protocol: registry